#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3309/ssi
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database: mysql
#    show-sql: true

#spring:
#  datasource:
#    url: jdbc:sqlserver://localhost
#    username: sa
#    password: P@55w0rd
#    platform: mssql
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    database: SQL_SERVER
#    show-sql: true
